### ISSUE TITLE
connection unexpectedly closed

### ISSUE THREAD

**Issue by parisni** [ktsr42/RsyncServerApp#2]
Hi. I get this error:

```bash
rsync --version
rsync  version 3.1.2  protocol version 31

rsync -razsc rsync://host:port/hash /tmp/
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [Receiver=3.1.2]
```

**Comment by maples3** [comment]
I receive a similar error.  Phone is a Motorola Moto z4 running Android 10.  I'm running the rsync command from cygwin on Windows 10.

```
Anthony@AnthonyInspiron ~
$ rsync --version
rsync  version 3.2.4dev  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, no hardlink-specials, symlinks, IPv6, atimes,
    batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv,
    symtimes, prealloc, stop-at, no crtimes
Optimizations:
    no SIMD, asm, openssl-crypto
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

Anthony@AnthonyInspiron ~
$ rsync -rtvPh Anthony/Nextcloud/music/ rsync://192.168.200.238:42521/48fc85/Music/ -n
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.4dev]
```

Any ideas?  @parisni, did you ever find a resolution?

**Comment by ktsr42** [comment]
Hi, I have an idea as to what the issue might be. Not sure when I will get around to putting in a fix though.

I will let you know.

**Comment by magnetux** [comment]
so i'm not alone here, wish developer can fix this problem, may be add log capability?

please combine my issue with this, as i have already opened the issue
https://github.com/ktsr42/RsyncServerApp/issues/5

Listing is Okay
```shell
V:\bin\rsync-3.2.3>rsync.exe rsync://192.168.0.136:37213/123352/Movies/"Backed Up"/
drwxr-xr-x          3,488 2021/11/22 12:18:37 .
-rw-r--r--    391,335,065 2021/11/10 03:23:29 (Drakorasia.blog) SRIJ Eps - 01 540p.mkv
-rw-r--r--    322,042,735 2021/11/11 09:13:09 (Drakorasia.blog) SRIJ Eps - 02 540p (1).mkv
-rw-r--r--    602,382,058 2021/11/16 08:28:56 (Drakorasia.blog) SRIJ Eps - 03 720p.mkv
-rw-r--r--    514,736,800 2021/11/17 18:16:52 (Drakorasia.blog) SRIJ Eps - 04 720p.mkv
```

I can get file from my android to windows 10, but i'm try to push file from windows to android, this is what happened
```shell
V:\bin\rsync-3.2.3>rsync.exe -avr --progress /cygdrive/V/tmp/push/ rsync://192.168.0.136:37213/123352/Movies/"Backed Up"/
sending incremental file list
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
```

anyone know why? because there is no log feature in the program, it is rather difficult to find out what errors have occurred.

**Comment by ktsr42** [comment]
So there are two separate issues at play here. First, the protocol negotiation was changed by the main rsync implementation in a non-backwards compatible way with release 3.1.2. Even forcing the rsync client to use an earlier protocol version does not avoid this. This issue was fixed in version 3 of the app, which is available on Fdroid.

Using the `--progress` is separate from that and currently not supported. Giving this flag to the client will still result in a a disconnect from the app. For the moment, just don't use it and everything should work.

**Comment by d-wid** [comment]
> The protocol negotiation was changed by the main rsync implementation in a non-backwards compatible way with release 3.1.2. Even forcing the rsync client to use an earlier protocol version does not avoid this. This issue was fixed in version 3 of the app, which is available on Fdroid.

I assume by version 3 you mean the one listed as 0.9.9 on F-droid? For some reason I still have the same issue even though the Rsync version on the client is also new enough.`

```
:~$ sudo rsync -avxHAXS rsync://192.168.bla.bla:blabl/blabla/ /tmp --dry-run
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.3]
:~$ rsync --version
rsync  version 3.2.3  protocol version 31
Copyright (C) 1996-2020 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, hardlink-specials, symlinks, IPv6, atimes,
    batchfiles, inplace, append, ACLs, xattrs, optional protect-args, iconv,
    symtimes, prealloc, stop-at, no crtimes
Optimizations:
    SIMD, asm, openssl-crypto
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

**Comment by ktsr42** [comment]
Can you try removing the flags? Something like `rsync --verbose --archive ...` works for me.

Background: For the purpose of negotiating the communication parameters the rsync protocol transmits the command-line flags from the client to the server. Yep.

This app is based on a library that only implements the core protocol for transferring files. Any flag that is not recognized simply throws an exception thereby dropping the connection. This applies even to things that are purely client-side like `--dry-run` or `--progress`.

**Comment by d-wid** [comment]
@ktsr42 I tried shortening it to -va instead of --verbose --archive to a similar result. I guess that might've been the issue?

Am I missing a list of available flags you wrote somewhere? The above is me copying the one I pasted into a backup script some time ago to make sure as much metadata as I can have doesn't get lost but obviously I am willing to skip some (especially if -a still works like you said)

**Comment by d-wid** [comment]
> @ktsr42 I tried shortening it to -va instead of --verbose --archive to a similar result. I guess that might've been the issue? Am I missing a list of available flags you wrote somewhere? The above is me copying the one I pasted into a backup script some time ago to make sure as much metadata as I can have doesn't get lost but obviously I am willing to skip some (especially if -a still works like you said)

My bad, what I hadn't tried was both reducing the flags to -av AND removing --dry-run.

The data transfer does work after I did.

**Comment by williamdes** [comment]
Same for me, it was the dry run flag..
